 <input list="Majors3" name="Majors3">
	<datalist id="Majors3">
 	 	<option value="Agricultural economics">
		<option value="Animal sciences">
		<option value="Food science">
		<option value="Environmental science">
		<option value="Forestry">
		<option value="Architecture">
		<option value="Journalism">
		<option value="Computer science">
		<option value="Mathematics teacher education">
		<option value="Architectural engineering">
		<option value="Chemical engineering">
		<option value="Civil engineering">
		<option value="Computer engineering">
		<option value="Mechanical engineering">
		<option value="Metallurgical engineering">
		<option value="Mining and mineral engineering">
		<option value="Molecular biology">
		<option value="Ecology">
		<option value="Neuroscience">
		<option value="Mathematics">
		<option value="Applied mathematics">
		<option value="Multi/interdisciplinary studies">
		<option value="Nutrition sciences">
		<option value="Music">
		<option value="Philosophy and religious studies">
		<option value="Theology and religious vocations">
		<option value="Physical sciences">
		<option value="Atmospheric sciences and meteorology">
		<option value="Chemistry">
		<option value="Physics">
		<option value="Psychology">
		<option value="Industrial and organizational psychology">
		<option value="Social psychology">
		<option value="Industrial and organizational psychology">
		<option value="Public administration">
		<option value="Social work">
		<option value="Criminology">
		<option value="Economics">
		<option value="Geography">
		<option value="Political science and government">
		<option value="Sociology">
		<option value="Visual and performing arts">
		<option value="Music">
		<option value="Health and medical administrative services">
		<option value="Nursing">
		<option value="Accounting">
		<option value="International business">
		<option value="History">
		</datalist>
	